"""empty message

Revision ID: 495e3e2e2f2b
Revises: 6f78816ab4e2
Create Date: 2024-08-16 21:53:50.770997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495e3e2e2f2b'
down_revision = '6f78816ab4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('requestee_username')
        batch_op.drop_column('requestor_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requestor_username', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('requestee_username', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
