"""Add year to Transaction model

Revision ID: 6d2e3f33e8ea
Revises: 495e3e2e2f2b
Create Date: 2024-08-19 11:45:38.348319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2e3f33e8ea'
down_revision = '495e3e2e2f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
