"""empty message

Revision ID: 883758fd01a5
Revises: 
Create Date: 2024-08-21 18:07:35.870869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883758fd01a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitor_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name=op.f('fk_friend_requests_invitee_id_users')),
    sa.ForeignKeyConstraint(['invitor_id'], ['users.id'], name=op.f('fk_friend_requests_invitor_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('fk_friendships_friend_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friendships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor', sa.Integer(), nullable=False),
    sa.Column('requestee', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requestee'], ['users.id'], name=op.f('fk_transactions_requestee_users')),
    sa.ForeignKeyConstraint(['requestor'], ['users.id'], name=op.f('fk_transactions_requestor_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('friendships')
    op.drop_table('friend_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
